### ISSUE TITLE
Mojo::DOM (and somehow applying this to Dancer2?)

### ISSUE THREAD

**Issue by cromedome** [PerlDancer/advent-calendar#50]
Joel, go wild with this one :)

**Comment by jberger** [comment]
So I've managed to let my invitation expire, sorry about that. Can you readd me @cromedome?

Here's my initial demo application: https://gist.github.com/jberger/dcd04205dffacbd6837cbe0600e72af5 The idea is using a hook and Mojo::DOM to post-process a response to upgrade http links to https. Obviously that method could be extended to any html rewriting but this seems relevant given the browser push to forbid http.

I'd appreciate any comments on the Dancer2 application itself since I'm not going to claim to be any kind of Dancer2 developer. I've basically just cargo cult-ed parts of [my article from 2018](http://advent.perldancer.org/2018/20) and used some of it too.

**Comment by cromedome** [comment]
That works. Short, sweet, and to the point!

**Comment by cromedome** [comment]
Done! Thanks @jberger !
